apiVersion: v2
name: tailscale-derp
description: Run a custom tailscale derp server on Kubernetes.
type: application
version: 0.17.3
appVersion: "v1.92.0"
sources:
  - "https://github.com/coreweave/tailscale-derp"
